AWSTemplateFormatVersion: "2010-09-09" 
Description: webserver
Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: corazon-key-pair
      ImageId: ami-07caf09b362be10b8 
      InstanceType: t2.micro
      Tags:
      - Key: name
        Value: webserver